packages:
  atuin:
    paths: [ atuin ]
    specfile_path: atuin.spec
    downstream_package_name: atuin
    upstream_package_name: atuin
    # Dummy actions we want to use the spec file as-is because we are doing
    # non-standard changes on top of it
    # Changes:
    # - Fix the License section with the %cargo_license_summary in the build.log
    # - Change the %cargo_install to a manual install command
    # - Move the default /etc/profile.d script to a separate `atuin-all-users` package
    # - Make bash-preexec a Recommends requirement for `atuin-all-users`
    actions:
      fix-spec-file: []
      create-archive:
        - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
  bash-preexec:
    # https://github.com/rcaloras/bash-preexec
    paths: [ bash-preexec ]
    specfile_path: bash-preexec.spec
    upstream_package_name: bash-preexec
    downstream_package_name: bash-preexec
    actions:
      fix-spec-file: []
      create-archive:
        - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'

srpm_build_deps:
  - rust2rpm

jobs:
  - &copr_build
    job: copr_build
    trigger: pull_request
    owner: lecris
    project: atuin
    targets:
      - fedora-rawhide
  - <<: *copr_build
    trigger: commit
    update_release: false
    owner: sramanujam
    project: atuin
    targets:
      - fedora-all
